### ISSUE TITLE
In dark mode, stickied post titles cannot be seen when selected

### ISSUE THREAD

**Issue by aluo123** [TheEnigmaBlade/leagueoflegends-css#15] opened 2015-10-01 22:34 UTC
![new theme issues](https://cloud.githubusercontent.com/assets/12616911/10235474/cac758e2-686a-11e5-9f95-b02686ff224d.png)

**Comment by TheEnigmaBlade** [comment] 2015-10-01 22:37
Duplicate of #12.

**Closed as completed by TheEnigmaBlade** 2015-10-01 22:37 UTC
Labels: duplicate, wontfix
