### ISSUE TITLE
Black flairs not visible on the sidebar

### ISSUE THREAD

**Issue by SW1FT** [TheEnigmaBlade/leagueoflegends-css#20] opened 2015-10-02 12:45 UTC
Example (using the CLG flair): 
![flairlol](https://cloud.githubusercontent.com/assets/6627739/10246745/de1ac658-690b-11e5-802e-6529d684bd25.png)

**Comment by TheEnigmaBlade** [comment] 2015-10-02 16:35
Duplicate of #3.

**Closed as completed by TheEnigmaBlade** 2015-10-02 16:35 UTC
Labels: duplicate
